### PR TITLE
updating user

### PR DESCRIPTION
**Pull request by TouanAin**

### CODE REVIEW

**Comment by TouanAin** [comment]
lgfm

**Comment by phamhoangha** [comment]
lgfm

**Comment by phamhoangha** [comment]
lgfm

**Comment by namlv** [comment]
lhtm

**Comment by ducmv** [comment]
lgfm

**Comment by anhnamxtanh** [comment]
lgfm

**Comment by TouanAin** [comment]
LGTM

**Comment by TouanAin** [comment]
LGTM

**Comment by TouanAin** [comment]
LGTM

**Comment by phamhoangha** [comment]
lgtm

**Comment by anhnamxtanh** [comment]
LGTM

**Comment by TouanAin** [comment]
LGTM

**Pull request merged**
